# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{call-fwd}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alexander Shvets"]
  s.date = %q{2010-06-06}
  s.description = %q{Enables/disables call forwarding feature for phone service.}
  s.email = %q{alexander.shvets@gmail.com}
  s.executables = ["cfwd", "call-fwd"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "Rakefile",
     "VERSION",
     "bin/call-fwd",
     "bin/call-fwd.bat",
     "bin/cfwd",
     "bin/cfwd.bat",
     "call-fwd.gemspec",
     "lib/call_fwd.rb",
     "lib/call_fwd/app.rb",
     "lib/call_fwd/call_fwd_service.rb",
     "lib/call_fwd/password_manager.rb",
     "lib/cfwd.rb",
     "lib/start.rb",
     "views/index.haml",
     "views/layout.haml",
     "views/login.haml",
     "views/stylesheet.sass"
  ]
  s.homepage = %q{http://github.com/shvets/call-fwd}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.requirements = ["none"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Enables/disables call forwarding feature.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

